### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by FabioZumbi12** [nylser/TreeDestroyage#6]
This is the logs:

```
-- Head --
Thread: Server Watchdog
Stacktrace:
	at net.mineguild.minecraft.treedestroyage.event.BreakBlockHandler.findBase(BreakBlockHandler.java:205)
	at net.mineguild.minecraft.treedestroyage.event.BreakBlockHandler.placeSapling(BreakBlockHandler.java:174)
	at net.mineguild.minecraft.treedestroyage.event.BreakBlockHandler.handle(BreakBlockHandler.java:149)
	at org.spongepowered.common.event.listener.BreakListener_BreakBlockHandler_handle96.handle(Unknown Source)
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368)
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:427)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207)
	at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:612)
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:531)
	at org.spongepowered.common.event.tracking.phase.packet.InteractionPacketState.unwind(InteractionPacketState.java:132)
	at org.spongepowered.common.event.tracking.phase.packet.InteractionPacketState.unwind(InteractionPacketState.java:71)
	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:211)
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:392)
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151)
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276)
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003)
```
Using 0.13 DEV
spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar
forge-1.12.2-14.23.2.2632-universal.jar

**Comment by nylser** [comment]
Closed with #7
